/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatransxw_PcmMix */

#ifndef _Included_com_mediatransxw_PcmMix
#define _Included_com_mediatransxw_PcmMix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatransxw_PcmMix
 * Method:    Mix
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_mediatransxw_PcmMix_Mix
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
